url: "http://dmcarroll.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/books" # the subpath of your site, e.g. /blog
title: ""
email: dan@dmcarroll.net
description: "Lists and reviews of my favorite books and authors."
twitter_username: FloriDanOnline
github_username: dan-carroll
