url: "http://dmcarroll.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/books" # the subpath of your site, e.g. /blog
title: "Dan's Reading List and Reviews"
email: dan@dmcarroll.net
description: "Lists and reviews of my favorite books and authors."
twitter_username: FloriDanOnline
github_username: dan-carroll

sass:
    style: compressed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  books:
    output: true
    permalink: /books/:path/
  authors:
    output: true
    permalink: /authors/:path/
