url: "http://dmcarroll.net/books" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Dan's Reading List and Reviews"
email: dan@dmcarroll.net
description: "Lists and reviews of my favorite books and authors."
twitter: https://twitter.com/FloriDanOnline
twitter_username: FloriDanOnline
github: https://github.com/dan-carroll
github_username: dan-carroll
facebook: https://www.facebook.com/floridan/
facebook_username: FloriDan
instagram: https://www.instagram.com/dcarroll809/
instagram_username: dcarroll809
linkedin: https://www.linkedin.com/in/dan-carroll-in-florida/
linkedin_username: dan-carroll-in-florida

sass:
    style: compressed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  tags:
    output: true
    permalink: /tags/:path/    
  reviews:
    output: true
    permalink: /reviews/:path/
  authors:
    output: true
    permalink: /authors/:path/
    sort_by: name_key
